### ISSUE TITLE
Mobile Responsive UI Issue

### ISSUE THREAD

**Issue by yamisagi** [neslihanatasever/jobSearchApp#2]
First of all, It's a very well-done project, congrats ! 
However, it seems that there are responsive design issues in the `navBar` & `searchDiv` sections. 
Once fixed, it will make the project even better, and you might also consider revisiting the filter function ✌🏻

<img width="1435" alt="SS" src="https://github.com/neslihanatasever/jobSearchApp/assets/84624853/78565f7a-d699-4db3-a4b6-85ac8e007f29">

**Comment by neslihanatasever** [comment]
Many thanks for the comments and feedback.
